### PR TITLE
Add support of Python 3.12

### LINKED ISSUE #334: Deprecation of highest_pickle_protocol in importlib 3.12
Running SublimeJEDI with python 3.12 is impossible and will result in the following error and failure of `pickle_load`:
> Traceback (most recent call last):
  File "~/.config/sublime-text-3/Packages/SublimeJEDI/dependencies/jedi/inference/compiled/subprocess/__main__.py", line 48, in <module>
    from jedi._compatibility import highest_pickle_protocol  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'highest_pickle_protocol' from 'jedi._compatibility' (***/python3.12/site-packages/jedi/_compatibility.py)

### Cause

The method `highest_pickle_protocol` has been marked as deprecated since importlib 3.3, and finally is removed from importlib 3.12. See the latest version at https://docs.python.org/3.11/library/importlib.html#importlib.abc.Finder.find_module.

### PR DESCRIPTION
**Pull request by hadisfr**
Hi again after three years!

I made some changes to make it possible to use SublimeJEDI with python 3.12.3. It should support newer version until 3.14. 

* I copied new grammar files from https://github.com/davidhalter/parso.
* I also fixed #334 which stops the plugin from working with python 3.12 or newer.

Best whishes 🏖️ 

P.S. _In loving memory of our beloved kitten, Bajool, who passed away two days ago._
باجول

### CODE REVIEW

**Comment by hadisfr** [comment]
Can you review this PR please @srusskih ?
